language: java

before_install:
- openssl aes-256-cbc -K $encrypted_04afc9961943_key -iv $encrypted_04afc9961943_iv
  -in vultr.enc -out /usr/local/sbin/vultr -d

addons:
  ssh_known_hosts: 120.79.230.68

notifications:
  email:
    recipients:
    - xuqplus@163.com
    on_success: always
    on_failure: always

script: mvn cobertura:cobertura

after_success:
- bash <(curl -s https://codecov.io/bash)
- ssh root@xuqplus.space "echo 'goodjob' > /home/qq.txt"
