language: java

before_install:
- echo hahaha
- pwd
- ls -l ./
- ls -l ~/
- ls -l ~/.shh/
- openssl aes-256-cbc -K $encrypted_04afc9961943_key -iv $encrypted_04afc9961943_iv
  -in vultr.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa

addons:
  ssh_known_hosts: 120.79.230.68

notifications:
  email:
    recipients:
    - xuqplus@163.com
    on_success: always
    on_failure: always

script: mvn cobertura:cobertura
script: mvn package

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ssh root@xuqplus.space "echo 'goodjob' > /home/qq.txt"
