language: java
env:
  global:
    secure: AoFo0kth2FIEG1jNi6oLrhT+jUUdK++0tP0SeXuKquUfqmMTTFZvcphMNqHzaa7CRVi/vkTpABhOBKq6qay8BF427ysoSPp9CptOCPpf6ivxgk9XGQsyjUvetC7O8dJ2XXo0rwO29zuL/oWEZkCvFzsRbGS6swAyCXB3dqFsJ3jBe0B/o8/8j/YyEQNT2RdgkgTJal0I2VjjYkRFyMhqJzmf0R/Fa24xnR+KGQVqtDooxL4q56QaZCus5Pwb5m8TeRMgIRnHBMaBC2dYn7mYAIVKiwaDBSbD5SWcyN7YRpGE4pqb2AXsMtBjlwSkZlINUMwNS934ZMMyOd67OhWzpj490MKBmOJPksGqtoqVxaoQGnKlTRlnJvDeNeV2bMV9Kz+hrj5wvhR5vaXEo47QQtV0ZjOJAsNwsEGl/DX9NdOJjlhvYqPY8sJ141snlfN/ke3wr1qUg7hp5lY3QNVtWkLYwHNNq5XrzG7fJArF1oMun6TT0XuxJGSlYaZhYKy+EJubiXzMwG/9kS5vYZxH/J+RP7swhojjrgMS9PtsL0qcML1CWG0dbfuz4FvfdC7t5fre40qiRu6j4DunZYL6UBk77mdbWfq4hCGU0pmwAiewv62yrVq/9pruhoMzGFr+MFmafdXSa+KlYF8G1ZDfjKKmk86EwbCKfAZAoK25WGM=
addons:
  ssh_known_hosts: 120.79.230.68
before_install:
- who
- pwd
- env
- openssl aes-256-cbc -K $encrypted_04afc9961943_key -iv $encrypted_04afc9961943_iv -in id_rsa.vultr.enc -out id_rsa.vultr -d
- chmod 600 id_rsa.vultr
- mysql -e "grant all privileges on *.* to test@'%' identified by '123456';"
- mysql -e "flush privileges;"
- docker login --username xuqplus --password $docker_hub_password
notifications:
  email:
    recipients:
    - xuqplus@163.com
    on_success: always
    on_failure: always
script:
- mvn package -DskipTests=true
- docker build -t xuqplus/adminlte . && docker push xuqplus/adminlte
after_success:
- bash <(curl -s https://codecov.io/bash)
- ssh -i id_rsa.vultr root@xuqplus.space "echo 'goodjob' >> /home/qq.txt"
