#!/bin/bash

container=$1
if [[ -z ${container} ]]; then
    echo container is null;
    exit 1
fi

server_name=$2
if [[ -z ${server_name} ]]; then
    echo server_name is null
    exit 1
fi

server_ip=$3
if [[ -z ${server_ip} ]]; then
    echo server_ip is null
    exit 1
fi

server_port=$4
if [[ -z ${server_port} ]]; then
    echo server_port is null
    exit 1
fi


export domain=xuqplus.space

export conf="server {
	listen 9999;
	server_name ${server_name}.${domain};

        proxy_set_header Host $server_name:$server_port;
        # not outermost nginx
        #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # outermost nginx
        proxy_set_header X-Forwarded-For $remote_addr;

	location / {
		proxy_pass http://${server_ip}:${server_port};
	}
}"

export confFile=${server_name}.${domain}

echo -e "${conf}" > ${confFile}
docker cp ${confFile} ${container}:/etc/nginx/sites-enabled/
rm ${confFile} > /dev/null

export tmp=`docker exec -i ${container} nginx -t 2>&1`

if [ $(echo ${tmp} | grep -c fail) != 0 ]; then
    if [ $(echo ${tmp} | grep -c success) -eq 0 ]; then
        docker exec -i ${container} rm /etc/nginx/sites-enabled/${confFile}
        echo ${confFile} nginx -t failed, deleted;
        echo ${tmp}
        exit 1
    fi
fi

if [ $(echo ${tmp} | grep -c fail) = 0 ]; then
    if [ $(echo ${tmp} | grep -c success) != 0 ]; then
        echo ${confFile} nginx -t success;
    fi
fi