#!/bin/bash

container=$1
if [[ -z ${container} ]]; then
    echo container is null;
    exit 1
fi

export tmp=`docker exec -i ${container} nginx -t 2>&1`

if [ $(echo ${tmp} | grep -c fail) = 0 ]; then
    if [ $(echo ${tmp} | grep -c success) != 0 ]; then
        echo ${container} nginx -t success;
        docker exec -i ${container} nginx -s reload;
        echo ${container} nginx reloaded;
        exit 0
    fi
fi

echo ${container} nginx -t fail;
exit 1