#!/bin/bash

container=$1
if [[ -z ${container} ]]; then
    echo container is null;
    exit 1
fi

if [ $(docker exec -it ${container} nginx -t | grep -c fail) = 0 ]; then
    if [ $(docker exec -it ${container} nginx -t | grep -c success) != 0 ]; then
        echo ${container} nginx -t success;
        docker exec -it ${container} nginx -s reload;
        echo ${container} nginx reloaded;
        exit 0
    fi
fi

echo ${container} nginx -t fail;
exit 1